--- Makefile.orig	2012-03-07 23:25:33.687477306 -0800
+++ Makefile	2012-03-07 23:31:48.838928882 -0800
@@ -207,7 +207,8 @@
 		MUTT_SMIME_OUTLOOK_COMPAT	"SMIME outlook compatible"	on \
 		MUTT_SMTP			"Enable SMTP relay support"	off \
 		MUTT_TRASH_PATCH		"Enable trash folder support"	off \
-		MUTT_XML			"Use XML tools for docu"	on
+		MUTT_XML			"Use XML tools for docu"	on \
+		MUTT_GMAIL			"Enable Gmail IMAP Ext patch"	off
 .endif
 
 PLIST=		${WRKDIR}/PLIST
@@ -367,6 +368,11 @@
 	@${PATCH} ${PATCH_ARGS} -p1 < ${PATCHDIR}/extra-patch-parent-child-match
 .endif
 
+.if defined(WITH_MUTT_GMAIL)
+post-patch::
+	@${PATCH} ${PATCH_ARGS} < ${PATCHDIR}/extra-patch-gmail
+.endif
+
 .if defined(WITHOUT_MUTT_FLOCK)
 CONFIGURE_ARGS+=	--disable-flock
 .else
